/**
 * API Route: Generate Smile
 * Converted from Supabase Edge Function: generate-smile
 * 
 * Uses Google Gemini's image generation to create smile variations.
 */
import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { storage } from '@/lib/storage';

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

export async function OPTIONS() {
    return new NextResponse('ok', { headers: corsHeaders, status: 200 });
}

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const { image_base64, image_path, prompt_options } = body;

        const apiKey = process.env.GOOGLE_API_KEY;
        if (!apiKey) throw new Error('GOOGLE_API_KEY not configured');

        // Get image data
        let imageBase64 = image_base64;

        if (!imageBase64 && image_path) {
            const buffer = await storage.downloadFileAsBuffer('scans', image_path);
            imageBase64 = buffer.toString('base64');
        }

        if (!imageBase64) {
            throw new Error('No image data provided');
        }

        // Build the generation prompt
        const variationPrompt = prompt_options?.variationPrompt || 'Natural smile enhancement';
        const aspectRatio = prompt_options?.aspectRatio || '1:1';

        const prompt = `Generate a photorealistic image of this exact same person with an enhanced, natural-looking smile. 
${variationPrompt}

Critical requirements:
- Keep the EXACT same face, skin tone, hair, and features
- Keep the EXACT same background and lighting
- Only modify the smile/teeth area
- The result must look completely natural and unedited
- Match the original image's aspect ratio: ${aspectRatio}`;

        // Call Gemini's image generation
        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${apiKey}`,
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{
                        parts: [
                            { text: prompt },
                            {
                                inline_data: {
                                    mime_type: 'image/jpeg',
                                    data: imageBase64
                                }
                            }
                        ]
                    }],
                    generationConfig: {
                        responseModalities: ['IMAGE', 'TEXT'],
                        responseMimeType: 'text/plain',
                    }
                })
            }
        );

        if (!response.ok) {
            const errText = await response.text();
            console.error('Gemini API Error:', errText);
            throw new Error(`Gemini API Error: ${response.status}`);
        }

        const data = await response.json();

        // Extract generated image
        const parts = data.candidates?.[0]?.content?.parts || [];
        const imagePart = parts.find((p: any) => p.inline_data?.mime_type?.startsWith('image/'));

        if (!imagePart?.inline_data?.data) {
            // Check for safety filter
            const finishReason = data.candidates?.[0]?.finishReason;
            if (finishReason === 'SAFETY') {
                throw new Error('SAFETY: Image generation was blocked by safety filters');
            }
            throw new Error('No image generated by Gemini');
        }

        // Upload generated image to storage
        const imageBuffer = Buffer.from(imagePart.inline_data.data, 'base64');
        const fileName = `smile_${Date.now()}_${Math.random().toString(36).slice(2, 8)}.jpg`;
        const filePath = `smiles/${fileName}`;

        const publicUrl = await storage.uploadFile('generated', filePath, imageBuffer, 'image/jpeg');

        // If analysis_id provided, link it
        if (prompt_options?.analysis_id) {
            await db.query(
                'UPDATE analysis_results SET result = result || $1 WHERE id = $2',
                [JSON.stringify({ generated_image: filePath }), prompt_options.analysis_id]
            );
        }

        return NextResponse.json({
            success: true,
            public_url: publicUrl,
            path: filePath,
        }, { headers: corsHeaders });

    } catch (error: any) {
        console.error('[generate-smile] Error:', error);
        return NextResponse.json(
            { success: false, error: error.message },
            { headers: corsHeaders, status: 500 }
        );
    }
}
